version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    - compiler: msvc

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: .\build\scripts\appveyor.install.windows.ps1

build_script:
  - ps: $build_type="$env:configuration";
  - ps: $third_party="$env:temp\dogen_deps\dogen_deps_vc14_windows_amd64";
  - ps: $target = "ALL_BUILD run_windows_green_tests";
  - ps: cd $project_dir
  - ps: .\build\scripts\build.windows.ps1 -build_type $build_type -compiler $env:compiler -third_party $third_party -target $target
  - ps: if ($build_type -eq "Release") {
            cd $project_dir\build\output\$env:compiler\$build_type;
            $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.10\bin";
            $env:WIX = "C:\Program Files (x86)\WiX Toolset v3.10\bin";
            cpack -G WIX -C Release;
        }

artifacts:
  - path: build/output/msvc/Release/stage/pkg/dogen-1.0.01-Windows-AMD64.msi
    name: x86_64 MSI

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/90f86ee1561e8f3c3056
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy:
  - provider: BinTray
    username: mcraveiro
    api_key:
      secure: aeW66aeBxn5W4wOnb5Ae9L1/dYRsAyWiJatWTpKPSwEgR1diIFPUUeSqQ4jTxeF8
    subject: domaindrivenconsulting
    repo: Dogen
    package: Dogen
    artifact: build/output/msvc/Release/stage/pkg/dogen-1.0.01-Windows-AMD64.msi
    version: 1.0.01
    publish: true
    override: true
