version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    # - generator: "MinGW Makefiles"
    - COMPILER: msvc

configuration:
  - Debug
  - Release

platform:
  - x64

clone_depth: 1

install:
  - cmd: set BUILD_DIR=build/scripts
  - ps: write-host ./$env:BUILD_DIR/appveyor.install.windows.ps1

  #
  # cmake
  #
  - cinst cmake --version 3.4.3
  - cmd: cmake --version

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - cmd: set PATH=%PATH%:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=C:\MinGW\bin;%PATH%

build_script:
  - cmd: set THIRD_PARTY="C:/TEMP/dogen_deps_vc14_windows_amd64";
  - cmd: set TARGET="package run_windows_green_tests";
  - cmd: set BUILD_TYPE="%configuration%"
  - ps: .\$env:BUILD_DIR\build.windows.ps1 -build_type $env:BUILD_TYPE -compiler $env:COMPILER -third_party $env:THIRD_PARTY -target $env:TARGET

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/414a6b420bdcead8eec0
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
