version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    # - generator: "MinGW Makefiles"
    - generator: "Visual Studio 14 2015 Win64"

configuration:
  # - Debug
  - Release

platform:
  - x64

install:
    - cinst cmake

    # conan
    - cmd: echo "Downloading conan..."
    - ps: wget http://downloads.conan.io/latest_windows -OutFile conan_installer.exe
    - cmd: conan_installer.exe /VERYSILENT
    - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
    - cmd: conan --version

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - cmd: echo %PATH%
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=C:\MinGW\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: cd build
  - cmd: mkdir output
  - cmd: cd output
  - cmd: conan install ../.. --file=.conanfile.txt
  - cmd: cmake ../.. -DCMAKE_BUILD_TYPE=%configuration% -G "%generator%"

build_script:
    - cmd: cmake --build . --config "%configuration%" --target quilt.cpp

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/0beb0c7103fcf4e4f262
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
