version: 1.0.9.{build}

branches:
    only:
        - master

image:
  - Visual Studio 2017

environment:
  matrix:
    - compiler: msvc
  matrix:
    allow_failures:
      - compiler: clang-cl

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: .\build\scripts\appveyor.install.windows.ps1
  - ps: $env:Path += "c:\third_party\installs\ninja\bin"

build_script:
  - ps: $build_type="$env:configuration";
  - ps: $third_party="$env:temp\dogen_deps\dogen_deps_vc14_windows_amd64";
  - ps: $target = "ALL_BUILD run_windows_green_tests";
  - ps: $compiler = $env:compiler;
  - ps: cd $project_dir
  - ps: .\build\scripts\build.windows.ps1 -build_type $build_type -compiler $compiler -third_party $third_party -target $target
  - ps: if ($build_type -eq "Release" -and $compiler -eq "msvc") {
            cd $project_dir\build\output\$env:compiler\$build_type;
            $env:Path += ";" + $env:WIX;
            cpack -G WIX -C Release;
        }

artifacts:
  - path: build/output/msvc/Release/stage/pkg/dogen-1.0.09-Windows-AMD64.msi
    name: x86_64 MSI

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b6954fae540d73da033b
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy:
  - provider: BinTray
    username: mcraveiro
    api_key:
      secure: aeW66aeBxn5W4wOnb5Ae9L1/dYRsAyWiJatWTpKPSwEgR1diIFPUUeSqQ4jTxeF8
    subject: masd-project
    repo: main
    package: dogen
    artifact: build/scripts/wget.exe
    version: 1.0.09
    publish: false
    override: true
