version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    # - generator: "MinGW Makefiles"
    - COMPILER: msvc

configuration:
  - Debug
  - Release

platform:
  - x64

clone_depth: 5

install:
  #
  # cmake
  #
  - cinst cmake --version 3.4.3
  - cmd: cmake --version
  - cmd: set BUILD_DIR=build/scripts
  - ps: .\${BUILD_DIR}\appveyor.install.windows.ps1

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - cmd: set PATH=%PATH%:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=C:\MinGW\bin;%PATH%
  - ps: .\${BUILD_DIR}\appveyor.install.windows.ps1

build_script:
  - cmd: set THIRD_PARTY="/tmp/dogen_deps/dogen_deps_clang_7_3_0_osx_amd64";
  - cmd: set TARGET="package run_windows_green_tests";
  - cmd: set BUILD_TYPE="%configuration%"
  - ps: .\${BUILD_DIR}\build.windows.ps1 ${BUILD_TYPE} ${COMPILER} ${TARGET}

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/414a6b420bdcead8eec0
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
