version: 1.0.9.{build}

branches:
    only:
        - master

image:
  - Visual Studio 2017

environment:
  matrix:
    - compiler: msvc
    - compiler: clang-cl

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: $env:Path += "c:\third_party\installs\ninja\bin"

build_script:
  - ps: $build_type="$env:configuration";
  - ps: $third_party="$env:temp\dogen_deps\dogen_deps_vc14_windows_amd64";
  - ps: $target = "ALL_BUILD run_windows_green_tests";
  - ps: $compiler = $env:compiler;
  - ps: cd $project_dir

artifacts:
  - path: build/scripts/wget.exe
    name: x86_64

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b6954fae540d73da033b
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy:
  - provider: BinTray
    username: mcraveiro
    api_key:
      secure: aeW66aeBxn5W4wOnb5Ae9L1/dYRsAyWiJatWTpKPSwEgR1diIFPUUeSqQ4jTxeF8
    subject: mcraveiro
    repo: Dogen
    package: Dogen
    artifact: build/scripts/wget.exe
    version: 1.0.09
    publish: false
    override: true
