version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    - generator: "MinGW Makefiles"
    - generator: "Visual Studio 14 2015 Win64"

configuration:
  - Debug
  - Release

platform:
  - x64

configuration:
  - Release

install:
    - cmd: choco install mingw
    - cmd: choco install cmake
    - cmd: choco upgrade cmake
    - cmd: cmake --version

    # conan
    - cmd: echo "Downloading conan..."
    - ps: wget http://downloads.conan.io/latest_windows -OutFile conan_installer.exe
    - cmd: conan_installer.exe /VERYSILENT
    - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
    - cmd: conan --version

build_script:
    - cmd: cd build
    - cmd: mkdir output
    - cmd: cd output
    - cmd: conan install ../..
    - cmd: cmake ../.. -G "%generator%"
    - cmd: cmake --build . --config "%configuration%"
