version: 1.0.9.{build}

branches:
    only:
        - master

image:
  - Visual Studio 2017

environment:
  matrix:
    - compiler: clang-cl
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x86_amd64
      GENERATOR: "Ninja"

    - compiler: msvc
      GENERATOR: "Visual Studio 15 2017 Win64";

matrix:
  allow_failures:
    - compiler: clang-cl

configuration:
  - Release
  - Debug

platform:
  - x64

clone_depth: 1

install:
  - ps: $project_dir="$pwd";
  - ps: .\build\scripts\appveyor.install.windows.ps1
  - ps: $env:Path += ";C:\third_party\installs\Ninja"
  - ps: $env:Path += ";" + $env:WIX;
  - ps: $env:CMAKE_TOOLCHAIN_FILE = "c:\third_party\installs\vcpkg-export\scripts\buildsystems\vcpkg.cmake"

before_build:
  - if DEFINED MSVC_SETUP_PATH call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: $env:BUILD_PROVIDER = "appveyor"
  - ps: $env:BUILD_COMMIT = $env:APPVEYOR_REPO_COMMIT
  - ps: $env:BUILD_NUMBER = $env:APPVEYOR_BUILD_VERSION
  - ps: $env:BUILD_TIMESTAMP = Get-Date -format "yyyy/MM/dd HH:mm:ss"
  - ps: $BUILD_TYPE = "$env:configuration";
  - ps: $COMPILER = $env:compiler;
  - ps: ctest --extra-verbose --script ".ctest.cmake,configuration_type=${BUILD_TYPE},generator=${GENERATOR},compiler=${COMPILER}";

artifacts:
  - path: build/output/msvc/Release/stage/pkg/dogen-1.0.09-Windows-AMD64.msi
    name: x86_64 MSI

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/b6954fae540d73da033b
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Email
    to:
      - marco.craveiro@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy:
  - provider: BinTray
    username: mcraveiro
    api_key:
      secure: aeW66aeBxn5W4wOnb5Ae9L1/dYRsAyWiJatWTpKPSwEgR1diIFPUUeSqQ4jTxeF8
    subject: masd-project
    repo: main
    package: dogen
    artifact: build/output/msvc/Release/stage/pkg/dogen-1.0.09-Windows-AMD64.msi
    version: 1.0.09
    publish: true
    override: true
