image: fedora:rawhide
script:
  - cd build
  - mkdir output
  - cd output
  - export CTEST_OUTPUT_ON_FAILURE=1
  - cmake ${GIT_REPO} -G Ninja
  - ninja -j2 run_all_specs

notify:  
  email:
    recipients:
      - marco.craveiro@gmail.com
