# -*- mode: yaml; tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2012 Kitanda <info@kitanda.co.uk>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
sudo: required
dist: trusty
language: cpp

matrix:
  # allow_failures:
  #   - os: osx
  include:
    # - os: osx
    #   compiler: clang
    #   env: BUILD_TYPE=Release
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release DEPLOY="1" COMPILER="gcc"
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release COMPILER="clang"
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COMPILER="gcc"
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug COMPILER="clang"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then source ./build/scripts/travis.install.linux.sh; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then source ./build/scripts/travis.install.osx.sh; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH=$PATH:~/conan; fi

script:
  - export PROJECT="`pwd`"
  - export THIRD_PARTY="/tmp/dogen_deps/dogen_deps_gcc_5.3_linux_amd64"
  - export TARGET="package run_all_specs"
  - ${PROJECT}/build/scripts/build.linux.sh ${BUILD_TYPE} ${COMPILER} ${THIRD_PARTY} ${TARGET}
  - sudo dpkg -i stage/pkg/dogen_*_amd64-applications.deb
  - cd /tmp
  - /usr/bin/dogen.knitter --version

notifications:
  email:
    recipients:
      - marco.craveiro@gmail.com
    on_success: change
    on_failure: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/db7439afa782608b5654
    on_success: always
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: UdotUzhLJ7GcmwyJlpqcsvWsXxuWjoswXG7intkgxKeD5vkIT6Ng2v7ik6c/4uO9wXJ9uWV8/X/EzdZhWqFjiamMljsmFGcy4Bt37oqP6oxdlRyO/KrLM1E/xtmA1kZppuY4njCqzZnMslyzyMtsl+DH3zseOL7GQIbkL5xbecI=
  file_glob: true
  file: stage/pkg/*.deb
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: "${DEPLOY} = 1"
