# -*- mode: yaml; tab-width: 4; indent-tabs-mode: nil -*-
#
# Copyright (C) 2012 Kitanda <info@kitanda.co.uk>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
sudo: required
dist: trusty
language: cpp
osx_image: xcode8

git:
  depth: 5

matrix:
  allow_failures:
    - os: osx
  include:
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release COMPILER="clang"
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug COMPILER="clang"
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release DEPLOY="1" COMPILER="gcc"
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release COMPILER="clang"
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COMPILER="gcc"
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug COMPILER="clang"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - export PROJECT="`pwd`"
  - export BUILD_DIR=${PROJECT}/build/scripts
  - source ${BUILD_DIR}/travis.install.${TRAVIS_OS_NAME}.sh

script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export THIRD_PARTY="/tmp/dogen_deps/dogen_deps_gcc_5.3_linux_amd64"; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export TARGET="package run_all_tests"; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export THIRD_PARTY="/tmp/dogen_deps/dogen_deps_clang_7_3_0_osx_amd64"; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export DYLD_LIBRARY_PATH="/tmp/dogen_deps/dogen_deps_clang_7_3_0_osx_amd64/lib"; fi

  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export TARGET="package run_all_tests"; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH=${THIRD_PARTY}/bin:${PATH}; fi
  - ${BUILD_DIR}/build.${TRAVIS_OS_NAME}.sh ${BUILD_TYPE} ${COMPILER} ${THIRD_PARTY} ${TARGET}
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then ${BUILD_DIR}/test_package.sh; fi

notifications:
  email:
    recipients:
      - marco.craveiro@gmail.com
    on_success: change
    on_failure: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/db7439afa782608b5654
      - https://buildtimetrend.herokuapp.com/travis
    on_success: always
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: UdotUzhLJ7GcmwyJlpqcsvWsXxuWjoswXG7intkgxKeD5vkIT6Ng2v7ik6c/4uO9wXJ9uWV8/X/EzdZhWqFjiamMljsmFGcy4Bt37oqP6oxdlRyO/KrLM1E/xtmA1kZppuY4njCqzZnMslyzyMtsl+DH3zseOL7GQIbkL5xbecI=
  file_glob: true
  file: stage/pkg/*.deb
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: "${DEPLOY} = 1"

deploy:
  provider: bintray
  file: "build/scripts/bintray.json"
  user: mcraveiro
  key:
    secure: IrFRrzzMnnFzj2s2hYctnvMjTf7HRe5uQVPcioAjbuNrxXX5XYmRH6ce8osxoRhcpQYS9ppCmrt8VbRBB57piWS3yKfM6WftDrmNQil7XwqowKAKm/VuX6K5psjJHRCYoNUAovwvfLmaLIWvVd+I+NkU48EXvflClXx13Qp8GtU=
  on:
    tags: true
    branch: master
    condition: "${DEPLOY} = 1"
