language: cpp

compiler:
  # - clang # disabled due to gcc STL
  - gcc

before_install:
  # boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  
  # cmake
  - sudo add-apt-repository -y ppa:kalakris/cmake

  # g++4.9
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # boost. install all for now.
  - sudo apt-get install libboost1.55-all-dev 
  
  # cmake
  - sudo apt-get install cmake

  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script: 
  - export GIT_REPO="`pwd`"
  - cd ..
  - mkdir output
  - cd output
  - cmake ${GIT_REPO}
  # for now lets not make -j2 package
  - make -j2 run_all_specs
  
notifications:
  email:
    recipients:
      - marco.craveiro:gmail.com
    on_success: [change]
    on_failure: [always]

deploy:
  provider: releases
  api_key:
    secure: UdotUzhLJ7GcmwyJlpqcsvWsXxuWjoswXG7intkgxKeD5vkIT6Ng2v7ik6c/4uO9wXJ9uWV8/X/EzdZhWqFjiamMljsmFGcy4Bt37oqP6oxdlRyO/KrLM1E/xtmA1kZppuY4njCqzZnMslyzyMtsl+DH3zseOL7GQIbkL5xbecI=
  file: stage/pkg/*.deb
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

webhooks:
    urls:
      - https://webhooks.gitter.im/e/db7439afa782608b5654
    on_success: change
    on_failure: always
    on_start: false
