version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    - VSVER: Visual Studio 14 2015 Win64

platform:
  - x64

configuration:
  - Release

install:
    - cmd: choco install cmake
    - cmd: choco upgrade cmake
    - cmd: cmake --version

    # conan
    - cmd: echo "Downloading conan..."
    - ps: wget https://s3-eu-west-1.amazonaws.com/conanio-production/downloads/conan-win_0_5_0.exe -OutFile conan_installer.exe
    - cmd: conan_installer.exe /VERYSILENT
    - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
    - cmd: conan --version

before_build:
    - cmd: nuget restore ./packages.config -packagesdirectory packages
    - ps: Get-ChildItem -Path ./packages -Recurse
      
build_script:
    - cmd: cd build
    - cmd: mkdir output
    - cmd: cd output
    - cmd: conan install ../..
    - cmd: cmake ../.. -G "%VSVER%"
    - cmd: cmake --build . --config Release
