version: 2.2.{build}

branches:
    only:
        - master

environment:
  matrix:
    - VSVER: Visual Studio 14 2015 Win64

platform:
  - x64

configuration:
  - Release

install:
    - cmd: choco install cmake
    - cmd: choco upgrade cmake
    - cmd: cmake --version

    # conan
    - cmd: echo "Downloading conan..."
    - ps: wget https://s3-eu-west-1.amazonaws.com/conanio-production/downloads/conan-win_0_5_0.exe -OutFile conan_installer.exe
    - cmd: conan_installer.exe /VERYSILENT
    - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
    - cmd: conan --version

before_build:
    - cmd: nuget restore ./packages.config -packagesdirectory packages
      
build_script:
    - cmd: cd build
    - cmd: mkdir output
    - cmd: cd output
    - cmd: conan install ../..
    - cmd: set CMAKE_INCLUDE_PATH=C:\projects\dogen\packages\libxml2.2.7.8.7\build\native\include;C:\projects\dogen\packages\libiconv.1.14.0.11\build\native\include
    - cmd: set CMAKE_LIBRARY_PATH=C:\projects\dogen\packages\libxml2.redist.2.7.8.7\build\native\bin\v110\x64\Release\dynamic\cdecl;C:\projects\dogen\packages\libiconv.redist.1.14.0.11\build\native\bin\v110\x64\Release\dynamic\cdecl
    - cmd: cmake ../.. -G "%VSVER%"
    - cmd: cmake --build . --config Release
